default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: beach_resort
  username: bewld-devs
  password: Abzedar2

production:
  <<: *default
  database: beach_resort_prod
  username: beach_resort
  password: <%= ENV['BEACH_RESORT_PASSWORD'] %>
